#!/usr/bin/env bash
set -x

# Window manager
sudo pacman -Sy i3 i3lock

# Essentials
sudo pacman -Sy zsh fzf git ssh# tools

# tools
sudo pacman -Sy tmux kitty

# Utils
sudo pacman -Sy parcellite imagemagick scort
