#!/usr/bin/env /bin/bash
# my daily check routine

CMD="sudo doit update"
echo "doit update"
echo $CMD
eval $CMD

echo "pacman update"
sudo pacman -Syu

# showing my dotfiles status
cd ~/git/pessoal/dotfiles
git status
cd -

