#!/usr/bin/env bash
set -x

echo "aptitude"

sudo apt-get install -y aptitude

echo "essentials"

sudo aptitude install -y ssh

echo "dev tools"

sudo aptitude install -y httpie git

echo "tools"

sudo aptitude install -y tmux kitty zsh

echo "Installing utils"

sudo aptitude install -y default-jdk

echo "medias and extras"

sudo aptitude install -y ubuntu-restricted-extras vlc

# For laptops
# todo - check

echo "laptops"

sudo aptitude install -y tlp tlp-rdw tp-smapi-dkms acpi-call-dkms thermald
