#!/bin/sh

if ! [ -x "$(command -v aptitude)" ]; then
  echo "aptitude not found. Using apt-get."
  sudo apt-get update && sudo apt-get upgrade
  #echo 'Error: aptitude is not installed. Use apt-get.'
  #exit 1
else
  echo "aptitude found. Using aptitude."
  sudo aptitude update && sudo aptitude safe-upgrade
fi

if [ -f /var/run/reboot-required ]
then
    echo "\n\nReboot required!"
fi
