#!/bin/sh

aptitude_installed=$(dpkg -l aptitude)
echo $aptitude_installed

err=$(dpkg -l err)
echo $err

sudo aptitude update && sudo aptitude safe-upgrade

if [ -f /var/run/reboot-required ]
then
    echo "Reboot required!"
fi
