#!/bin/sh
set mode -x
scp ~/git/icons4u/infra/vivo/vms/prod/cache1.server/varnish/default.vcl root@proxy1.p.vivo:/etc/varnish
scp ~/git/icons4u/infra/vivo/vms/prod/cache1.server/varnish/default.vcl root@proxy2.p.vivo:/etc/varnish
ssh root@proxy2.p.vivo "/etc/init.d/varnish restart"
ssh root@proxy1.p.vivo "/etc/init.d/varnish restart"
