#!/bin/sh

if ! [ -x "$(command -v aptitude)" ]; then
  echo 'Error: aptitude is not installed. Use apt-get.'
  exit 1
fi

sudo aptitude update && sudo aptitude safe-upgrade

if [ -f /var/run/reboot-required ]
then
    echo "\n\nReboot required!"
fi
