#!/bin/bash

echo "=> Initializing"

echo "=> dumping"

dumpfilename=$(date +%s)
pathdumpfile="/tmp/${dumpfilename}"

dump

echo "=> creating temp database"
create_temp_database

dbtempname="dsea_$(date +%s)"

echo "=> restoring in dev with temp name"
restore_temp_database

echo "=> closing all connections"

echo "=> renaming database dsea"

echo "=> renaming temp prod copy to dsea"

function dump {
  cd /tmp
  pg_dump -v -h pg.dsea.uerj.br -U rafael -F tar -f ${pathdumpfile} dsea
  echo "Arquivo salvo em ${pathdumpfile}"
}

function create_temp_database {
  psql -h pgdev.dsea.uerj.br -U rafael -c "create database ${dbtempname}"
}

function restore_temp_database {
  
}
