#!/bin/sh

echo "=> Initializing"

echo "=> dumping"
dump

echo "restoring in dev with temp name"

echo "closing all connections"

echo "renaming database dsea"

echo "renaming temp prod copy to dsea"

function dump {
  cd /tmp
  dumpfilename=$(date +%s)
  pathdumpfile="/tmp/${dumpfilename}"
  pg_dump -v -h pg.dsea.uerj.br -U rafael -F tar -f ${pathdumpfile} dsea
  echo "Arquivo salvo em ${pathdumpfile}"
  cd -
}
