#!/bin/sh

aptitude_installed=$(-f /usr/bin/aptitude)
echo $aptitude_installed

# err=$(dpkg -l err)
# echo $err

sudo aptitude update && sudo aptitude safe-upgrade

if [ -f /var/run/reboot-required ]
then
    echo "\n\nReboot required!"
fi
